name: deploy dev
on:
  push:
    branches:
      - develop

jobs:
  config:
    name: ðŸ›  ðŸ”¨ Setup Version
    runs-on: [ self-hosted, Linux, standard ]
    outputs:
      APP_VERSION: ${{ steps.config.outputs.APP_VERSION }}
      APP_NAME: ${{ steps.config.outputs.APP_NAME }}
    steps:

      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup version
        id: config
        run: |-
          APP_NAME=$(node -p "require('./package.json').name")
          APP_VERSION=$(node -p "require('./package.json').version")
          echo "app_name=$APP_NAME" >> $GITHUB_OUTPUT
          echo "app_name = $APP_NAME"
          echo "app_version=$APP_VERSION" >> $GITHUB_OUTPUT
          echo "app_version = $APP_VERSION"

  docker:
    runs-on: ubuntu-latest
    steps:
      -
        name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      #-
        #name: Login to Docker Hub
        #uses: docker/login-action@v3
        #with:
          #username: ${{ secrets.DOCKERHUB_USERNAME }}
          #password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: user/app:latest